def configure(conf):
    pass

def build(bld):
    lib = bld.stlib(
        target = 'AC_Guidance',
        features = 'cxx',
        includes = ['.'],
        source = bld.path.ant_glob('*.cpp'),
        name = 'AC_Guidance',
        use = ['HAL'],  # <<--- tells waf to link HAL symbols
        cxxflags = ['-Wno-error'],  # optional if you're hitting Werror
    )
    lib.source = [
        'Guidance.cpp',
        'Frame.cpp',
        'Frame.h',
        'Quaternion.cpp',
        'Quaternion.hcpp',
        'Vehicle.cpp',
        'Vehicle.h',
        
    ]
    lib.includes = ['.']
